networks:
  1panel-network:
    external: true
services:
  zashboard:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/kashinoleg/zashboard:latest
    labels:
      createdBy: Apps
    networks:
      1panel-network:
        aliases:
        - ${CONTAINER_NAME}
    ports:
    - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${DATA_PATH}:/app/data
