services:
  photopea:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}:${APP_VERSION}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8887
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
