services:
  llamaindex:
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    image: ${IMAGE}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${HOST_IP}:${PANEL_APP_PORT_HTTP}:8000"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL}
      - OLLAMA_EMBEDDING_DISABLED=${OLLAMA_EMBEDDING_DISABLED}
      - PERSIST_DIR=${PERSIST_DIR}
      - ENABLE_HUMAN_IN_LOOP=${ENABLE_HUMAN_IN_LOOP}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}:/app/data
    labels:
      createdBy: Apps
